[project]
name = "helpdesk-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn[standard]>=0.52.4",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]  # erros, pyflakes, imports, upgrades, bugbear

[tool.ruff.format]
quote-style = "double"